apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contacts-app
  template:
    metadata:
      labels:
        app: contacts-app
    spec:
      containers:
        - name: contacts-app
          image: <DOCKER_IMAGE_NAME>
          ports:
            - containerPort: 5000

