apiVersion: v1
kind: Service
metadata:
  name: contacts-service
spec:
  selector:
    app: contacts-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
